hiuasd

diff --git a/.github/workflows/generate-env.yml b/.github/workflows/generate-env.yml
--- a/.github/workflows/generate-env.yml
+++ b/.github/workflows/generate-env.yml
@@ -14,11 +14,7 @@ on:
 
 jobs:
   generate-env:
-    strategy:
-      matrix:
-        os: [ubuntu-latest, windows-latest, macos-latest]
-    runs-on: ${{ matrix.os }}
-    
+    runs-on: ubuntu-latest
     environment: ${{ github.ref_name == 'main' && 'main' || github.ref_name == 'dev' && 'dev' || '' }}
 
     outputs:
@@ -66,6 +62,12 @@ jobs:
            cat .env.local
           fi
 
+      - name: Show current directory
+        run: pwd
+
+      - name: List files here
+        run: ls -la
+
       - name: Set artifact path
         id: set-path 
         run: |
@@ -78,19 +80,21 @@ jobs:
             exit 1
           fi
 
-      - name: Find env file path
-        id: find-env
+      - name: Check if env file exists
         run: |
-          envfile=$(find . -type f -name ".env.*" | head -n 1 | sed 's|^\./||')
-          echo "Found env file: $envfile"
-          echo "envfile=$envfile" >> $GITHUB_OUTPUT
-         
-      - name: Upload env artifact 
-        uses: ./
+          if [ -f "${{ steps.set-path.outputs.path }}" ]; then
+            echo "File '${{ steps.set-path.outputs.path }}' exists."
+          else
+            echo "File '${{ steps.set-path.outputs.path }}' does NOT exist."
+            exit 1  # fail the job if file doesn't exist
+          fi
+
+      - name: Upload env artifact
+        uses: actions/upload-artifact@v4
         with:
-          name: env-file
-          path: ${{ steps.find-env.outputs.envfile }}
-        
+          name: env-file-${{ steps.set-branch.outputs.branch }}
+          path: ${{ steps.set-path.outputs.path }}
+
   # use-env:
   #   needs: generate-env
   #   runs-on: ubuntu-latest
